apiVersion: v1
kind: Service
metadata:
  name: playwright-framework-service
spec:
  selector:
    app: playwright-framework
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer